# Generated by Django 3.2 on 2021-07-02 17:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_ordereditem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='ordertime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 17, 31, 20, 525301, tzinfo=utc), verbose_name='время заказа'),
        ),
    ]
