# Generated by Django 3.2 on 2021-07-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20210702_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordertime',
            field=models.DateTimeField(verbose_name='время заказа'),
        ),
    ]
