# Generated by Django 3.2 on 2021-07-04 07:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_remove_order_ordered_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='ordered_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.product', verbose_name='Заказанный продукт'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(50)], verbose_name='количество'),
        ),
    ]
