# Generated by Django 3.2 on 2021-07-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20210704_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditem',
            old_name='ordered_product',
            new_name='product',
        ),
    ]
