# Generated by Django 3.2 on 2021-07-20 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_alter_order_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена товара'),
        ),
    ]
