# Generated by Django 3.2 on 2021-07-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_alter_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='calltime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время звонка'),
        ),
    ]
