# Generated by Django 3.2 on 2021-07-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_calltime'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cash', 'Наличностью'), ('card', 'Электронно')], default='cash', max_length=64, verbose_name='способ оплаты'),
        ),
    ]
