# Generated by Django 3.2 on 2021-07-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Необработанный'), ('processed', 'Обработанный')], default='unprocessed', max_length=64, verbose_name='статус'),
        ),
    ]
