# Generated by Django 3.2 on 2021-07-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_restaurantcoordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantcoordinates',
            name='lat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantcoordinates',
            name='lng',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
