# Generated by Django 3.2 on 2021-07-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_auto_20210728_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantcoordinates',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantcoordinates',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
    ]
