# Generated by Django 3.2 on 2021-07-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_auto_20210728_0113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantcoordinates',
            options={'verbose_name': 'координаты мест', 'verbose_name_plural': 'координаты мест'},
        ),
        migrations.AlterField(
            model_name='restaurantcoordinates',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantcoordinates',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
