# Generated by Django 3.2 on 2021-07-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_restauranttoclientdistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranttoclientdistance',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
