# Generated by Django 3.2 on 2021-07-28 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0059_alter_restauranttoclientdistance_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.product', verbose_name='заказанный продукт'),
        ),
        migrations.AlterField(
            model_name='restaurantcoordinates',
            name='address',
            field=models.CharField(max_length=64, unique=True, verbose_name='название'),
        ),
        migrations.DeleteModel(
            name='RestaurantToClientDistance',
        ),
    ]
