# Generated by Django 3.2 on 2021-07-28 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0060_auto_20210729_0026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantCoordinates',
        ),
    ]
