# Generated by Django 3.2 on 2021-08-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0062_auto_20210801_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('cash', 'Наличностью'), ('card', 'Электронно')], db_index=True, max_length=64, verbose_name='способ оплаты'),
        ),
    ]
