# Generated by Django 3.2 on 2021-08-20 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0063_alter_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='foodcartapp.order'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='foodcartapp.product', verbose_name='заказанный продукт'),
        ),
    ]
